[package]
name = "pylex-lite"
version = "0.1.0"
authors = ["jakeroggenbuck <jakeroggenbuck2@gmail.com>"]
edition = "2018"

[lib]
name = "pylex_lite"
crate-type = ["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
